### ISSUE TITLE
list_user_accounts does not work

### ISSUE THREAD

**Issue by dragonwolfsp** [JessicaTegner/teamtalk.py#7]
Hello, I am trying to get a list of users with this code ``def __cmdGetUserAccounts__(self,server,messageContent):
		accounts=server.list_user_accounts()
		users=[]
		for a in accounts:
			if a.szUsername in messageContent: users.append(a)
		return users``
but when I try to run this code, I get the following error.
DEBUG:teamtalk.bot:Running event on_message
ERROR:teamtalk.bot:Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Ethan Jones\coding\ttServerManager\teamtalk\bot.py", line 161, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Ethan Jones\coding\ttServerManager\serverManager.py", line 46, in on_message
    responce=commandHandler.handleCommand(message,user,server)
  File "C:\Users\Ethan Jones\coding\ttServerManager\core\commands.py", line 40, in handleCommand
    elif param=="cmdUserAccounts": params["cmdUserAccounts"]=self.__cmdGetUserAccounts__(server,self.__cmdGetContent__(c,message.content))
  File "C:\Users\Ethan Jones\coding\ttServerManager\core\commands.py", line 48, in __cmdGetUserAccounts__
    accounts=server.list_user_accounts()
  File "C:\Users\Ethan Jones\coding\ttServerManager\teamtalk\server.py", line 197, in __getattr__
    return _get_tt_obj_attribute(self._user, name)
  File "C:\Users\Ethan Jones\coding\ttServerManager\teamtalk\server.py", line 197, in __getattr__
    return _get_tt_obj_attribute(self._user, name)
  File "C:\Users\Ethan Jones\coding\ttServerManager\teamtalk\server.py", line 197, in __getattr__
    return _get_tt_obj_attribute(self._user, name)
  [Previous line repeated 979 more times]
  File "C:\Users\Ethan Jones\coding\ttServerManager\teamtalk\server.py", line 194, in __getattr__
    if name in dir(self):
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by dragonwolfsp** [comment]
my fault for not making every thing async, o well, I fixed it
